config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'projects#index'
  resources :projects do
    resources :tasks do
    patch :done, on: :member
    end
    post :sort, on: :collection
  end
  namespace :api do
    resource :tinymce_images, only: :create
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/priority.rb
# frozen_string_literal: true

class Priority < ApplicationRecord
  has_many :tasks
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates :title, presence: true

  acts_as_list

  def self.reorder(order_params)
    order_params.each_with_index do |id, index|
      Project.find(id).update!(position: index + 1)
    end
  end
end

app/models/status.rb
# frozen_string_literal: true

class Status < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :project
  belongs_to :priority
  belongs_to :status

  has_one_attached :tinymce_image

  validates :title, presence: true
  default_scope { order(:created_at) }
end

app/controllers/api/tinymce_images_controller.rb
# frozen_string_literal: true

module Api
  class TinymceImagesController < ApplicationController
    def create
      blob = ActiveStorage::Blob.create_after_upload!(
        io: tinymce_image_params[:file],
        filename: tinymce_image_params[:file].original_filename,
        content_type: tinymce_image_params[:file].content_type
      )
      render json: {
        image: { url: url_for(blob) }
      }, content_type: 'text/html'
    end

    private

    def tinymce_image_params
      params.permit(:file)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def render_404
    render file: '/public/404.html', status: 404
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :project, only: %i[show edit update destroy], except: :sort
  protect_from_forgery except: [:sort]
  def index
    @projects = Project.all.order(:position)
    @task = Task.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, notice: 'Project was successfully added.'
    else
      render :new, alert: @project.errors.full_messages
    end
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: 'Project was successfully updated.'
    else
      render :edit, alert: @project.errors.full_messages
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_path, notice: 'Project was deleted successfully .'
    else
      redirect_to projects_path, alert: @project.errors.full_messages
    end
  end

  def sort
    Project.reorder(params[:project])
    head :no_content
  end

  private

  def project
    @project ||= begin
                   Project.find(params[:id])
                 rescue StandardError
                   nil
                 end
    render_404 unless @project
  end

  def project_params
    params.require(:project).permit(:title)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :task, only: %i[show edit update destroy done]

  def create
    task
    task.assign_attributes(task_params)
    if task.save
      redirect_to projects_path, notice: 'Task was successfully added.'
    else
      redirect_to projects_path, notice: 'Task was not added.'
    end
  end

  def edit
    task
  end

  def update
    if task.update(task_params)
      redirect_to projects_path, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if task.destroy
      redirect_to projects_path, notice: 'Task was deleted successfully .'
    else
      redirect_to projects_path, alert: task.errors.full_messages
    end
  end

  def done
    if task.update(status_id: params[:task][:status])
      redirect_to projects_path, notice: 'Task was mark as done.' if params[:task][:status] == '4'
      redirect_to projects_path, notice: 'Task is back to in_progress.' if params[:task][:status] == '2'
    else
      render projects_path, notice: ['Errors:', task.errors.full_messages.join(',')].join
    end
  end

  private

  def task
    @task ||= params[:id].present? ? tasks.find(params[:id]) : tasks.new
  end

  def tasks
    @tasks ||= project.tasks
  end

  def project
    @project ||= begin
      Project.find(params[:project_id])
                 rescue StandardError
                   nil
    end
  end

  def task_params
    params.require(:task).permit(:project_id, :title, :description, :deadline, :priority_id, :status_id, :tinymce_image)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= alertify_flash(wait: 20) %>
  </head>

  <body style= "background-color: #f0f8ff" >
    <%= yield %>
  </body>
</html>

app/views/projects/_checked.html.erb
<script>
$("#defaultUnchecked<%= task.id %>").click(function(e, parameters) {

    let nonUI = false;
    try {
        nonUI = parameters.nonUI;
    } catch (e) {}
    let checked = nonUI ? !this.checked : this.checked;
    $("#edit_task_<%= task.id %>").submit();
});
</script>

app/views/projects/_footer.html.haml
%p{style: "padding-bottom: 20px"}
.card-footer.bg-transparent.border-muted
  @olegshevtsov1

app/views/projects/_form.html.haml
= f.error_notification
= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
.form-inputs
  = f.input :title,
  placeholder: t('activerecord.models.project.attributes.title.placeholder')

app/views/projects/_header.html.haml
.card-header.bg-transparent.border-muted
  %h3
    %a{href: "/", style: "text-decoration: none"}
      SAMPLE TODO LISTS

app/views/projects/_index_task_form.html.haml
.row
  .col-12
    .input-group.input-group-lg
      .input-group-prepend
        %span{id: "inputGroup-sizing-lg",class: "input-group-text"}
          .custom-control.custom-checkbox
            = check_box_tag "defaultUnchecked#{task.id}",'',
              task.status.id == 4 ? true : false,
              class: 'custom-control-input'
            = label_tag "defaultUnchecked#{task.id}",'', class: 'custom-control-label'
      = text_field_tag :title, task.title, readonly: "true",
      class: "form-control",
      style: task.status.id == 4 ? "text-decoration: line-through" : ""
      .input-group-prepend
        %span{ class: "input-group-text text-primary", id: "inputGroup-sizing-lg"}
          = render partial: 'show_task_modal', locals: {project: project, task: task}
          %i.pl-1
          = link_to raw('<i class="fa fa-pencil-square-o fa-sm"></i>'), edit_project_task_path(project,task),
              class: 'btn.btn-p.text-primary',
              title: t('edit')
          %i.pl-1
          = link_to raw('<i class="fa fa-trash-o fa-sm"></i>'), project_task_path(project,task),
              class: 'btn.btn-p.text-primary',
              method: :delete,
              data: {confirm: 'Are you sure to remove this task?'},
              title: t('delete')
= render partial: 'checked', locals: {project: project, task: task}
= form_for task, url: done_project_task_path(project,task) do |f|
  = f.hidden_field :status, value: task.status.id == 4 ? 2 : 4

app/views/projects/_new_task_form.html.haml
= simple_form_for([project,@task]) do |f|
  .row
    .col-12
      .input-group.input-group-lg
        = f.text_field :title,as: :string, class: "form-control",  placeholder: t('activerecord.models.task.create_new')
        = f.hidden_field :project_id, value: project.id
        .input-group-prepend
          %span.input-group-text{id: "inputGroup-sizing-lg"}
            .plus.text-primary
              = f.submit ''

app/views/projects/_show_task_modal.html.haml
%button.btn.btn-p.text-primary{type: "button",data:{"toggle" => "modal", "target" => "#Modaltaskshow#{task.id}" }}
  %i.fa.fa-file-text.fa-sm{"aria-hidden" => "true"}


-#Modal
.modal.fade{id: "Modaltaskshow#{task.id}",tabindex:"-1", role: "dialog", aria:{"labelledby" => "ModalLabel#{task.id}", "hidden" => "true" }}
  .modal-dialog.modal-dialog-centered.modal-lg{role: "document"}
    .modal-content
      .modal-header
        %h2.modal-title.text-muted
          .show_project
            = project.title
        %button.close{type: "button", "data-dismiss" => "modal", "aria-label" => "Close"}
          %span{"aria-hidden" => "true"}
            &times;
      .modal-header
        %h6.modal-title.text-muted{id: "ModalLabel#{task.id}"}
          .row
            .col-4
              =t("activerecord.models.status.one")+":"+" "+task.status.title.to_s
            .col-4
              =t("activerecord.models.priority.one")+":"+" "+task.priority.title.to_s
            .col-4
              =t("activerecord.models.task.attributes.deadline.placeholder")+":"+" "+task.deadline.to_s

      .modal-body.text-muted{style: "text-align: left"}
        .show_task_title
          = task.title
        .show_task_description
          = task.description.to_s.html_safe
      .modal-footer
        %h6.modal-title.text-muted
        .modal-footer
        %h6.modal-title.text-muted{style: "text-align: left"}
          %button.btn.btn-primary{type: "button","data-dismiss" => "modal" }
            Close

app/views/projects/edit.html.haml
= simple_form_for(@project,html: { class: 'col-sm-12' }) do |f|
  .container.bg-faded
    %p.pt-4
    .card.border-muted.shadow.col-lg-6{style: "background-color: #f0f8ff"}
      .card-header.bg-transparent.border-muted
        %h4
          = t('activerecord.models.project.edit')
      .card-body.text-primary
        = render partial: "form", locals: { f: f }
      .card-footer.bg-transparent.border-muted
        .row
          .col-2
            = link_to t(:cancel), projects_path, class: 'btn btn-danger'
          .col-10{style: 'text-align: right'}
            %p=  f.submit t('save')

app/views/projects/index.html.haml
.container.bg-faded
  %p.pt-4
  .card.border-muted.shadow.lg-12{ id: "projects_sortable", data:{ "update-url" => sort_projects_path() }, style: "background-color: #f0f8ff" }
    = render 'header'
    - @projects.each do |project|
      .card-body.text-primary{id: "project_#{project.id}"}
        .row
          .col-1
            %i.handle.fa.fa-list-alt.fa-2x
          .col-9
            %a{href: "#"}
            .card-link.text-dark
            %h4
              = project.title
          .col-2{style: "text-align: right" }
            %span
              = link_to raw('<i class="fa fa-pencil-square-o fa-lg"></i>'), edit_project_path(project),
                class: 'btn.btn-p.text-primary',
                title: t('edit')
              = link_to raw('<i class="fa fa-trash-o fa-lg"></i>'), project_path(project),
                class: 'btn.btn-p.text-primary',
                method: :delete,
                data: {confirm: 'Are you sure to remove this project?'},
                title: t('delete')
        = render partial: 'new_task_form', locals: {project: project}
        %hr
        - project.tasks.each do |task|
          = render partial: 'index_task_form', locals: {project: project, task: task}
    %div.pt-2{style: "text-align: center;"}
      %a{href: new_project_path}
        %button.btn.btn-primary
          %i.fa.fa-plus.fa-lg
          Add TODO List
    = render 'footer'

app/views/projects/new.html.haml
= simple_form_for(@project,html: { class: 'col-sm-12' }) do |f|
  .container.bg-faded
    %p.pt-4
    .card.border-muted.shadow.col-lg-6{style: "background-color: #f0f8ff"}
      .card-header.bg-transparent.border-muted
        %h4
          = t('activerecord.models.project.create_new')
      .card-body.text-primary
        = render partial: "form", locals: { f: f }
      .card-footer.bg-transparent.border-muted
        .row
          .col-2
            = link_to t(:cancel), projects_path, class: 'btn btn-danger'
          .col-10{style: 'text-align: right'}
            %p=  f.submit t('create')

app/views/tasks/_form.html.haml
= f.error_notification
= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
.form-inputs
  = f.association :project,
      as: :select,
      label: t('activerecord.models.project.one'),
      label_method:  :title,
      include_blank: false

  = f.input :title,
      placeholder: t('activerecord.models.task.attributes.title.placeholder')

  = f.input :description,
      input_html: { class: 'tinymce', rows: 10, cols: 60 },
      placeholder: t('activerecord.models.task.attributes.description.placeholder')

  = tinymce(uploadimage_form_url: api_tinymce_images_path)

  = f.input :deadline,
      placeholder: t('activerecord.models.task.attributes.deadline.placeholder')

  = f.association :priority,
    as: :select,
    label: t('activerecord.models.priority.one'),
    include_blank: false

  = f.association :status,
      as: :select,
      label: t('activerecord.models.status.one'),
      label_method:  :title,
      include_blank: false

app/views/tasks/edit.html.haml
= simple_form_for([@project,@task],html: { class: 'col-sm-12' }) do |f|
  .container.bg-faded
    %p.pt-4
    .card.border-muted.shadow.col-lg-6{style: "background-color: #f0f8ff"}
      .card-header.bg-transparent.border-muted
        %h4
          = t('activerecord.models.task.edit')
      .card-body.text-primary
        = render partial: "form", locals: { f: f }
      .card-footer.bg-transparent.border-muted
        .row
          .col-2
            = link_to t(:cancel), projects_path, class: 'btn btn-danger'
          .col-10{style: 'text-align: right'}
            %p=  f.submit t('save')